- plumtree/src/main/java/org/apache/tuweni/plumtree/State.java
change made: 
- modified sendGossipMessage in plumtree to return the message hash
reason:
- once a message is gossiped, i would like to know the message hash so that I can ignore the message if it is gossiped back to the original sender
currently, i work around the issue in Artemis like this:
```java
public void onNewUnprocessedBlock(BeaconBlock block) {
Bytes bytes = block.toBytes();
state.sendGossipMessage(bytes);
// TODO: this will be modified once Tuweni merges https://github.com/apache/incubator-tuweni/pull/3
this.receivedMessages.put(Hash.sha2_256(bytes).toHexString(), true);
}
```
> Return message hash from sendGossipMessage in Plumtree

- crypto/src/main/java/org/apache/tuweni/crypto/sodium/SecretBox.java
- scuttlebutt-handshake/src/main/java/org/apache/tuweni/scuttlebutt/handshake/SecureScuttlebuttStream.java
After enough scuttlebutt RPC requests and responses, the program crashes with an `OutOfMemory` exception. This pull request frees the memory allocated by the wrapper for the native lib sodium.
> Fix memory leak.

- build.gradle
- ssz/src/main/java/org/apache/tuweni/ssz/SSZ.java
- ssz/src/main/java/org/apache/tuweni/ssz/SSZWriter.java
- ssz/src/test/java/org/apache/tuweni/ssz/BytesSSZWriterTest.java
Correct encoding behavior for vector of non-homogeneous Bytes.
Both vectors of homogeneous (fixed/exact) bytes and vectors of non-homogeneous bytes (which require a mixin) were encoded without the element size mixin. This corrects that behavior.
> Correct encoding behavior for vector of non-homogeneous Bytes.

- scuttlebutt-rpc/src/main/java/org/apache/tuweni/scuttlebutt/rpc/RPCCodec.java
- scuttlebutt-rpc/src/main/java/org/apache/tuweni/scuttlebutt/rpc/mux/RPCHandler.java
See the "source example" section of the protocol docs: https://ssbc.github.io/scuttlebutt-protocol-guide/#rpc-protocol
> On a server ending a scuttlebutt RPC stream, the client should send a final close message to close its end of the stream.

- scuttlebutt-rpc/src/main/java/org/apache/tuweni/scuttlebutt/rpc/mux/RPCHandler.java
This change makes sure a stream cannot be closed more than once as the protocol states that they should only be closed once from each end.
In fact, closing the stream more than once can crash the nodejs version of the server at the moment: ssbc/muxrpc#49
Additionally, I've added more debug logging to log outgoing requests, stream close messages and include the request numbers in the log statements.
> Prevent it being possible to close streams more than once and add logging

- scuttlebutt-handshake/src/main/java/org/apache/tuweni/scuttlebutt/handshake/SecureScuttlebuttStream.java
- scuttlebutt-rpc/src/test/java/org/apache/tuweni/scuttlebutt/rpc/mux/PatchworkIntegrationTest.java
I encountered a bug whereby RPC messages with a large body length (for example 20kb) resulted in the server closing the connection immediately. In the application I'm building with this library, there is a custom RPC handler which can accept large messages as parameters.
I've narrowed this down to being an issue with the `slice` method on `Bytes` in the `encrypt` method of `SecureScuttlebuttStream`. It would appear that the `.size()` method retains the size of the original array that backs the slice, despite the `offset` and `end` that are set. This means that body length is set wrong in the box-stream headers, and I'm assuming the server closes the connection because it reads garbage rather than a header when it starts reading from the end of the length.
You can reproduce this error by: …
> Fix bug with scuttlebutt boxstream segments not being formed properly

- eth/src/main/java/org/apache/tuweni/eth/Transaction.java
One issue that I've had is that you need the keypair to use the Transaction class. 
By making this function public, it is possible to prepare the transaction data to sign, sign it somewhere else, and then build the transaction object with the signature result
> make signatureData function public

- scuttlebutt-client-lib/src/main/java/org/apache/tuweni/scuttlebutt/lib/FeedService.java
- scuttlebutt-client-lib/src/main/java/org/apache/tuweni/scuttlebutt/lib/NetworkService.java
- scuttlebutt-client-lib/src/main/java/org/apache/tuweni/scuttlebutt/lib/ScuttlebuttClient.java
- scuttlebutt-client-lib/src/main/java/org/apache/tuweni/scuttlebutt/lib/SocialService.java
- scuttlebutt-client-lib/src/main/java/org/apache/tuweni/scuttlebutt/lib/model/Peer.java
- scuttlebutt-client-lib/src/main/java/org/apache/tuweni/scuttlebutt/lib/model/PeerStateChange.java
- scuttlebutt-client-lib/src/main/java/org/apache/tuweni/scuttlebutt/lib/model/Profile.java
- scuttlebutt-client-lib/src/main/java/org/apache/tuweni/scuttlebutt/lib/model/UpdateNameMessage.java
- scuttlebutt-client-lib/src/main/java/org/apache/tuweni/scuttlebutt/lib/model/query/AboutQuery.java
- scuttlebutt-client-lib/src/main/java/org/apache/tuweni/scuttlebutt/lib/model/query/AboutQueryResponse.java
- scuttlebutt-client-lib/src/main/java/org/apache/tuweni/scuttlebutt/lib/model/query/IsFollowingQuery.java
- scuttlebutt-client-lib/src/main/java/org/apache/tuweni/scuttlebutt/lib/model/query/IsFollowingResponse.java
- scuttlebutt-client-lib/src/main/java/org/apache/tuweni/scuttlebutt/lib/model/query/WhoAmIResponse.java
- scuttlebutt-client-lib/src/test/java/org/apache/tuweni/scuttlebutt/lib/FeedStreamTest.java
- scuttlebutt-client-lib/src/test/java/org/apache/tuweni/scuttlebutt/lib/PeerInfoTest.java
- scuttlebutt-client-lib/src/test/java/org/apache/tuweni/scuttlebutt/lib/SocialServiceTest.java
- scuttlebutt-rpc/src/main/java/org/apache/tuweni/scuttlebutt/rpc/RPCResponse.java
This change adds new functionality to the `NetworkService` service for querying peers that the server is connected to, and peers that it has in its gossip table and their connection state.
Additionally, it introduces a new `SocialService` to query the social graph (for follows, followers and friends) and update the instance's display name and view the display name of other users.
*Note*: These methods assume that certain RPC functions are available to call on the instance that is connected to as a client. These RPC functions are exposed by the `ssb-gossip`, `ssb-about` and `ssb-friends` plugins for `ssb-server`, which are used by most popular clients (patchwork, patchbay, manyverse.)
> Add functionality for querying scuttlebutt gossip table and social graph

- scuttlebutt/src/main/java/org/apache/tuweni/scuttlebutt/Identity.java
Some documentation stated that a parameter called publicKey should be the secret key
> Fix doc stating that the publicKey should be the secret key

- dependency-versions.gradle
commons-codec 1.12 has a minor information exposure vulnerability that is making Snyk complain.  (https://app.snyk.io/vuln/SNYK-JAVA-COMMONSCODEC-561518) Upgrade it to the latest version.
> Upgrade codec dependency

- units/src/main/java/org/apache/tuweni/units/bigints/UInt256.java
- units/src/test/java/org/apache/tuweni/units/bigints/UInt256Test.java
Hyperledger Besu has identified that converting between Bytes32 and
UInt256 is a performance bottleneck. In particular the current paths
force a large number of calls to org.apache.tuweni.bytes.Bytes::get and
org.apache.tuweni.bytes.Bytes::getInt, both megamorophic interface
methods that Hotspot cannot easily optimize.
The performance change is to go to straight primitive manipulation for
hot cases. This resulted in a 75% speedup in one ad-hoc benchmark
modeling a EVM Transaction execution.
> Performance - Faster UInt256/Bytes32 conversions

- units/src/main/java/org/apache/tuweni/units/bigints/UInt256.java
- units/src/test/java/org/apache/tuweni/units/bigints/UInt256Test.java
When using the optimized byte32 path the high bit for the signed bytes
get smeared when they are cast.  Also add tests that will fail when such
smearing occurs.
> Prevent signed ints smearing int UInt256

- hobbits/src/integrationTest/kotlin/org/apache/tuweni/hobbits/InteractionTest.kt
- hobbits/src/integrationTest/kotlin/org/apache/tuweni/hobbits/RelayerTest.kt
- io/src/test/java/org/apache/tuweni/io/ResourcesTest.java
Fix two issues breaking windows tests:
* Explicitly make hobbits UPD tests bind to 127.0.0.1 instead of 0.0.0.0.
Windows does not easily support binding to multiple interfaes for listening.
* Rely on java native URL creation for file resource tests.
fixes #81
> Fix Windows Tests

- toml/src/main/java/org/apache/tuweni/toml/JsonSerializer.java
- toml/src/test/java/org/apache/tuweni/toml/MutableTomlTableTest.java
Thank you for creating a great library.
This PR fixes a bug which is a toml feature can't convert toml object to Json strings by `toJson()` method in some cases. 
This JsonSerializer escapes  `'`. But, It does not need for Json.
Also, the JsonSerializer does not escape `"`. It should be escaped for Json.
> Fix escape on JsonSerializer of toml

- build.gradle
- dist/build.gradle
- eth-client/src/main/resources/logback.xml
- eth-reference-tests/build.gradle
- eth2-reference-tests/build.gradle
- gradle/check-licenses.gradle
* upgrade gradle wrapper to 6.3
* upgrade errorprone plugin to 1.2.1
* disable a few errorprone checks based on java version
* upgrade jacoco to 0.8.5
* apply missing license header
* explicitly opt into logback EPL1 license
* make submodule optional
* make src jar buildable
> Make build more resiliant

- concurrent-coroutines/src/test/kotlin/org/apache/tuweni/concurrent/coroutines/RetryableTest.kt
- io/src/main/java/org/apache/tuweni/io/file/Files.java
- kv/src/test/kotlin/org/apache/tuweni/kv/KeyValueStoreSpec.kt
Two general windows fixes:
* When deleting a file, sometimes windows insists it is in use.
In that case mark it as deleteOnExit, it's the best we can do.
* Sub-second delays and thread switching is not as reliable in windows.
Change an assert to accept a range of delays.
> Windows Testing Fixes

- eth/src/main/java/org/apache/tuweni/eth/Address.java
- eth/src/test/java/org/apache/tuweni/eth/PublicKeyToAddressTest.java
Transform pub key to an Ethereum account address.
> Add public key to address transformation

- dist/build.gradle
- gradle/check-licenses.gradle
Add a different NOTICE for binary distribution, including all dependencies with their license.
> Add a different NOTICE for binary distrib

- devp2p/src/main/kotlin/org/apache/tuweni/devp2p/EthereumNodeRecord.kt
Expose the bytes of the public key, so it's no longer required to expose the public key object itself.
Relates to #172
> Expose the bytes of the public key

- les/src/test/kotlin/org/apache/tuweni/les/LESSubProtocolHandlerTest.kt
- rlpx/src/main/java/org/apache/tuweni/rlpx/RLPxService.java
- rlpx/src/main/java/org/apache/tuweni/rlpx/vertx/VertxRLPxService.java
Expose the actual network interface used by the RLPx service, not just the port.
> Expose actual network interface

- les/src/test/kotlin/org/apache/tuweni/les/LESSubProtocolHandlerTest.kt
- rlpx/src/main/java/org/apache/tuweni/rlpx/RLPxService.java
- rlpx/src/main/java/org/apache/tuweni/rlpx/vertx/VertxRLPxService.java
Keep peers identified by their public key alive at all times.
> Add ability to keep peers alive explicitly

- bytes/src/main/java/org/apache/tuweni/bytes/Bytes32.java
- bytes/src/test/java/org/apache/tuweni/bytes/Bytes32Test.java
> Fix issue 168: Bytes32.wrap with offset is incorrect

- dist/NOTICE-binary
- dist/build.gradle
Case insensitive file systems don't like having to deal with a LICENSE file and license folder. Renaming license to license-reports.
> rename license folder to license-reports

- bytes/src/main/java/org/apache/tuweni/bytes/AbstractBytes.java
- bytes/src/main/java/org/apache/tuweni/bytes/ArrayWrappingBytes.java
- bytes/src/main/java/org/apache/tuweni/bytes/ConcatenatedBytes.java
- bytes/src/main/java/org/apache/tuweni/bytes/MutableArrayWrappingBytes.java
- bytes/src/main/java/org/apache/tuweni/bytes/MutableBufferWrappingBytes.java
- bytes/src/main/java/org/apache/tuweni/bytes/MutableByteBufWrappingBytes.java
- bytes/src/main/java/org/apache/tuweni/bytes/MutableByteBufferWrappingBytes.java
- bytes/src/test/java/org/apache/tuweni/bytes/BytesTest.java
- bytes/src/test/java/org/apache/tuweni/bytes/ConcatenatedBytesTest.java
- bytes/src/test/java/org/apache/tuweni/bytes/GuardedBytesTest.java
- bytes/src/test/java/org/apache/tuweni/bytes/MutableBytesTest.java
Use the Bytes hash code to perform equals, and cache it if possible.
> Make Bytes more performant by caching hashcode

- build.sh
Add dist build folder to the mounted folders when running build.sh, so folks can get the distributions by following the build.sh script
> Add dist to build

- eth/src/main/kotlin/org/apache/tuweni/eth/JSONRPCRequest.kt
- eth/src/main/kotlin/org/apache/tuweni/eth/JSONRPCResponse.kt
- ethstats/src/integrationTest/kotlin/org/apache/tuweni/ethstats/EthStatsReporterTest.kt
- jsonrpc/build.gradle
- jsonrpc/src/main/kotlin/org/apache/tuweni/jsonrpc/JSONRPCClient.kt
- jsonrpc/src/main/kotlin/org/apache/tuweni/jsonrpc/JSONRPCServer.kt
- jsonrpc/src/main/kotlin/org/apache/tuweni/jsonrpc/methods/MethodsHandler.kt
- jsonrpc/src/main/kotlin/org/apache/tuweni/jsonrpc/methods/Web3.kt
- jsonrpc/src/test/kotlin/org/apache/tuweni/jsonrpc/JSONRPCClientTest.kt
- jsonrpc/src/test/kotlin/org/apache/tuweni/jsonrpc/methods/MethodsHandlerTest.kt
This is the barebones implementation of a JSON-RPC server that is able to understand HTTP requests for batch and single requests, pass them to a controller for fulfillment, and send back the data.
The PR has one example of a function fulfilled by Ethereum JSON-RPC.
> Initial implementation of JSON-RPC server

- devp2p-eth/src/main/kotlin/org/apache/tuweni/devp2p/eth/EthHandler.kt
- devp2p-eth/src/main/kotlin/org/apache/tuweni/devp2p/eth/EthHandler66.kt
- devp2p-eth/src/main/kotlin/org/apache/tuweni/devp2p/eth/EthHelloHandler.kt
An issue reported by the network crawler: you cannot assume that the protocol negotiated is eth/64, you have to pick whichever is used by the connection.
> Pick the eth subprotocol that was negotiated

- .github/workflows/assemble.yml
- .github/workflows/checks.yml
- .github/workflows/docs.yml
- .github/workflows/integration-tests.yml
- .github/workflows/license-checks.yml
- .github/workflows/test-windows.yml
- .github/workflows/test.yml
Avoid runaway test runners that would run for all 6 hours.
> Add timeout for all jobs so none run past 30 minutes

- dist/docker/tuweni.Dockerfile
Remove the apt-cache when building with Docker.
> clean up docker apt cache

- dns-discovery/src/main/kotlin/org/apache/tuweni/discovery/DNSDaemon.kt
- dns-discovery/src/main/kotlin/org/apache/tuweni/discovery/DNSResolver.kt
- metrics/src/main/kotlin/org/apache/tuweni/metrics/MetricsService.kt
This PR contains two commits. In one I am improving the warning message to include an information about the failed domain name. The second commit replaces SimpleResolver with ExtendedResolver. The ExtendedResolver has a retry policy and balancing of the load. When trying this changes on Besu I did not get the errors that I got with the SimpleResolver.
fixes issue #345
> Dns resolver issues

- crypto/src/main/java/org/apache/tuweni/crypto/Hash.java
Resolves a major performance degradation in `Hash` when libsodium is not available.  Previously every hash operation would try to load sodium which involves listing multiple directories to try to find the library and creating and throwing an exception.
Now when sodium is found to be unavailable `USE_SODIUM` is set to false to avoid repeatedly trying to load it.  Additionally applications can set a system property to completely disable use of libsodium (at least for Teku using it causes immediate `OutOfMemoryError`).
> Resolve libsodium performance degradation

- bytes/build.gradle
- bytes/src/main/java/org/apache/tuweni/bytes/ConcatenatedBytes.java
- bytes/src/test/java/org/apache/tuweni/bytes/ConcatenatedBytesTest.java
Override the implementation of `update(MessageDigest)` in `ConcatenatedBytes` to avoid copying the concatenated values into a temporary array.
> Add optimised update(MessageDigest) implementation for ConcatenatedBytes

- net/src/main/java/org/apache/tuweni/net/tls/FileBackedFingerprintRepository.java
- net/src/test/java/org/apache/tuweni/net/tls/FileBackedFingerprintRepositoryTest.java
Do not convert identifier to lower case when parsing file in FileBackedFingerprintRepository. Converting to lowercase results in identifier not found when mixed case common name is presented.
> Do not convert identifier to lower case when parsing file in FileBackedFingerprintRepository

- eth-client-app/build.gradle
- eth-client-app/src/main/kotlin/org/apache/tuweni/ethclient/BootnodeApp.kt
- eth-client-app/src/main/resources/bootnode.toml
- eth-client/src/main/kotlin/org/apache/tuweni/ethclient/EthereumClient.kt
- eth-client/src/main/kotlin/org/apache/tuweni/ethclient/EthereumClientConfig.kt
Adds a separate start script, and the necessary configuration and bindings, to have the ethereum client run as a bootnode.
Fixes #174
> Add bootnode script

- concurrent/src/main/java/org/apache/tuweni/concurrent/ExpiringMap.java
- concurrent/src/test/java/org/apache/tuweni/concurrent/ExpiringMapTest.java
- devp2p-eth/src/main/kotlin/org/apache/tuweni/devp2p/eth/EthClient.kt
- devp2p-eth/src/main/kotlin/org/apache/tuweni/devp2p/eth/EthClient66.kt
use ExpiringMaps instead of HashMaps for EthClient and EthClient66
This way, we will see requests expire after a bit. By default, the timeout is set to 10 minutes.
fixes #255
> use ExpiringMaps instead of HashMaps for EthClient and EthClient66

- dns-discovery/src/main/kotlin/org/apache/tuweni/discovery/DNSResolver.kt
Only log, the number of resolved nodes at INFO level, when the list of nodes is not empty, to avoid having a lot of log lines with "Resolved 0 nodes" that could confuse the user
fixes #370
> Log at DEBUG level when no nodes are resolved

- dependency-versions.gradle
see https://github.com/apache/incubator-tuweni/issues/373
https://www.sourceclear.com/vulnerability-database/security/integer-overflow/java/sid-7705
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-18928
Signed-off-by: Stefan Pingel <stefan.pingel@consensys.net>
> Update antlr4 version (Issue 373)

- dns-discovery/src/main/kotlin/org/apache/tuweni/discovery/DNSDaemon.kt
Refreshing DNS happens regularly enough and is reliable enough that changing this to DEBUG from INFO will eliminate log noise.
Signed-off-by: Justin Florentine <justin+github@florentine.us>
> turns down logging output to debug on DNS refresh

- ssz/src/main/java/org/apache/tuweni/ssz/BytesSSZReader.java
- ssz/src/test/java/org/apache/tuweni/ssz/BytesSSZReaderTest.java
Current implementation when using `reader.readFixedBytesList` handles elements as variable size. Added a test to clarify this and fixed
> ssz: Fix reader.readFixedBytesList

- .github/workflows/docs.yml.disable
Fixes the doc build by disabling it while https://github.com/Kotlin/dokka/issues/2572 is occurring.
> fix docs build, disable for now

- bytes/src/main/java/org/apache/tuweni/bytes/AbstractBytes.java
- bytes/src/main/java/org/apache/tuweni/bytes/Bytes.java
- bytes/src/main/java/org/apache/tuweni/bytes/BytesValues.java
Hello, I found a couple of tweaks for the conversions from bytes to hexadecimal strings and vice versa. 
from the numbers I get on my machine (ryzen 5900x)
* from bytes to hex string at least 2x better
* from hex string to bytes at least 2x better
I have a branch in my fork with the benchmarks if anyone wants to compare the numbers on different cpus, they can be run with './gradlew jmh'
[https://github.com/rudygt/incubator-tuweni/tree/benchmarks](url)
pd: do we have any project/benchmark already in the repo where the improvements in the bytes package could be seen? (tying to find out how these changes help/hurt real use cases)
Thanks!
```
Benchmark                                        Mode  Cnt      Score   Error  Units
BasicBenchmark.toHexByteBufferCandidate         thrpt    2 …
```
> speed up hex string to bytes and back

- bytes/src/main/java/org/apache/tuweni/bytes/Bytes.java
- bytes/src/main/java/org/apache/tuweni/bytes/DelegatingBytes.java
- bytes/src/main/java/org/apache/tuweni/bytes/DelegatingMutableBytes.java
- bytes/src/main/java/org/apache/tuweni/bytes/MutableArrayWrappingBytes.java
- bytes/src/main/java/org/apache/tuweni/bytes/MutableBufferWrappingBytes.java
- bytes/src/main/java/org/apache/tuweni/bytes/MutableByteBufWrappingBytes.java
- bytes/src/main/java/org/apache/tuweni/bytes/MutableByteBufferWrappingBytes.java
- bytes/src/main/java/org/apache/tuweni/bytes/MutableBytes.java
Several changes aimed at speeding up copyTo:
* DelgateingBytes delegates more calls to its delegate
* Bulk `set` method for setting more than one byte
* Defaulting Mutable Bytes to ByteArrays
> Speed up copyTo operation 

- bytes/src/main/java/org/apache/tuweni/bytes/ConstantBytes32Value.java
- bytes/src/test/java/org/apache/tuweni/bytes/Bytes32Test.java
Fix a problem where 32-byte constant values would not slice properly.
Fixes #445
> fix issue with constant bytes values slicing

- bytes/src/main/java/org/apache/tuweni/bytes/Bytes.java
- bytes/src/test/java/org/apache/tuweni/bytes/BytesTest.java
Fixes a corner case of bytes comparisons if both objects are only representing zero bytes, but they have different sizes.
> fix zero compares of different lengths

- jsonrpc/src/main/kotlin/org/apache/tuweni/jsonrpc/JSONRPCClient.kt
- jsonrpc/src/main/kotlin/org/apache/tuweni/jsonrpc/JSONRPCServer.kt
- jsonrpc/src/main/kotlin/org/apache/tuweni/jsonrpc/methods/MethodsHandler.kt
While the jsonrpc proxy sends the correct headers on the client side (to the node) the server is missing the content-type completely. Most frameworks assume `application/octet-stream` then and this introduces issues with downstream apps. This PR adds the specification `application/json` .
At INFO level it logged the whole response data 2 times, one via `println` which is impossible to disable by config.  Depending on the calls used this can cause tens of MBs per minute of logs. Removes the println and reduces the very verbose logging to debug level.
> jsonrpc: fix content-type header and response logging

- concurrent/src/main/java/org/apache/tuweni/concurrent/ExpiringMap.java
- concurrent/src/main/java/org/apache/tuweni/concurrent/ExpiringSet.java
- concurrent/src/test/java/org/apache/tuweni/concurrent/ExpiringMapTest.java
- concurrent/src/test/java/org/apache/tuweni/concurrent/ExpiringSetTest.java
Allow to set a global expiry listener for ExpiringMap and ExpiringSet that gets called unless a specific expiry listener is set on the entry.
Fixes #122
> Add a global expiration listener

- .github/workflows/assemble.yml
- .github/workflows/checks.yml
- .github/workflows/docs.yml.disable
- .github/workflows/integration-tests.yml
- .github/workflows/license-checks.yml
- .github/workflows/test.yml
- .github/workflows/test_referencetests.yml
- build.gradle
- gradle/build.Dockerfile
- gradle/wrapper/gradle-wrapper.properties
Use the docker image gradle tool instead of installing the jar on every run.
Upgrade gradle to 7.6 for both the CI image and the main build.
Use the docker image gradle tool instead of installing the jar on every run.
> Upgrade gradle to 7.6 in the docker image and in the build.

- eth-client/src/main/kotlin/org/apache/tuweni/ethclient/EthereumClient.kt
- eth-client/src/main/kotlin/org/apache/tuweni/ethclient/EthereumClientConfig.kt
Use a config setting to set the client service name instead of hardcoding to "tuweni". "tuweni" remains the default value.
Fixes #258
> Use a config setting to set the client service name

- devp2p-eth/src/integrationTest/kotlin/org/apache/tuweni/devp2p/eth/ConnectToAnotherNodeTest.kt
- devp2p-eth/src/integrationTest/kotlin/org/apache/tuweni/devp2p/eth/SendPendingTransactionsTest.kt
- devp2p-proxy/src/integrationTest/kotlin/org/apache/tuweni/devp2p/proxy/SendDataToAnotherNodeTest.kt
- eth-client/src/main/kotlin/org/apache/tuweni/ethclient/EthereumClient.kt
- eth-client/src/main/kotlin/org/apache/tuweni/ethclient/EthereumClientConfig.kt
- eth-crawler/src/main/kotlin/org/apache/tuweni/eth/crawler/CrawlerApp.kt
- rlpx/src/integrationTest/java/org/apache/tuweni/rlpx/vertx/VertxAcceptanceTest.java
- rlpx/src/integrationTest/java/org/apache/tuweni/rlpx/vertx/VertxRLPxServiceTest.java
- rlpx/src/main/java/org/apache/tuweni/rlpx/vertx/VertxRLPxService.java
Implements support for max number of connections from RLPx.
Fixes #285
> Allow to configure max clients of rlpx service
