apache/incubator-tuweni

devp2p/src/main/kotlin/org/apache/tuweni/devp2p/EthereumNodeRecord.kt
fix ENR encoding, was written excessive bytes, so decoding was not working
=> ENR encoding fixture

concurrent/build.gradle, concurrent/src/test/java/org/apache/tuweni/concurrent/DefaultCompletableAsyncCompletionTest.java, concurrent/src/test/java/org/apache/tuweni/concurrent/DefaultCompletableAsyncResultTest.java
=> Add more coverage of concurrent methods

ethstats/src/test/java/org/apache/tuweni/ethstats/AuthMessageTest.java, ethstats/src/test/java/org/apache/tuweni/ethstats/BlockStatsTest.java, ethstats/src/test/java/org/apache/tuweni/ethstats/TxStatsTest.java
=> Add ethstats coverage

rlpx/src/test/java/org/apache/tuweni/rlpx/RLPxConnectionFactoryTest.java, units/src/test/java/org/apache/tuweni/units/bigints/UInt64Test.java
=> Add more coverage for rlpx

bytes/src/test/java/org/apache/tuweni/bytes/DelegateBytes32Test.java, bytes/src/test/java/org/apache/tuweni/bytes/DelegateBytes48Test.java, crypto/src/test/java/org/apache/tuweni/crypto/sodium/AuthTest.java, crypto/src/test/java/org/apache/tuweni/crypto/sodium/KeyExchangeTest.java, ethstats/src/test/java/org/apache/tuweni/ethstats/NodeStatsTest.java, toml/src/test/java/org/apache/tuweni/toml/MutableTomlArrayTest.java
=> More coverage

bytes/src/main/java/org/apache/tuweni/bytes/Bytes.java, bytes/src/test/java/org/apache/tuweni/bytes/BytesTest.java, junit/src/test/java/org/apache/tuweni/junit/BouncyCastleExtensionTest.java, junit/src/test/java/org/apache/tuweni/junit/VertxExtensionTest.java, rlpx/src/main/java/org/apache/tuweni/rlpx/EthereumIESEncryptionEngine.java
=> coverage for bytes

concurrent/src/test/java/org/apache/tuweni/concurrent/DefaultCompletableAsyncCompletionTest.java, concurrent/src/test/java/org/apache/tuweni/concurrent/DefaultCompletableAsyncResultTest.java, concurrent/src/test/java/org/apache/tuweni/concurrent/ExpiringMapTest.java
Add more coverage for AsyncResult
=> Add more coverage for AsyncResult

hobbits-relayer/src/integrationTest/kotlin/org/apache/tuweni/relayer/RelayerAppTest.kt, hobbits-relayer/src/main/kotlin/org/apache/tuweni/relayer/RelayerApp.kt
Adds a test that checks stopping the relayer app works well.
This bit is flippant in coverage tests, creating weird false signals in coverage reports.
=> Add a test that checks stopping the app

.github/workflows/master-pr-build.yml, build.bat
built.bat doesn't run gradle assemble... fixing that.
=> Gradle assemble doesn't run on Windows

devp2p/src/integrationTest/kotlin/org/apache/tuweni/devp2p/v5/DefaultNodeDiscoveryServiceTest.kt, devp2p/src/main/kotlin/org/apache/tuweni/devp2p/DiscoveryService.kt, devp2p/src/main/kotlin/org/apache/tuweni/devp2p/EthereumNodeRecord.kt, devp2p/src/main/kotlin/org/apache/tuweni/devp2p/v5/NodeDiscoveryService.kt, devp2p/src/main/kotlin/org/apache/tuweni/devp2p/v5/storage/RoutingTable.kt, devp2p/src/test/kotlin/org/apache/tuweni/devp2p/ENRResponsePacketTest.kt, devp2p/src/test/kotlin/org/apache/tuweni/devp2p/EthereumNodeRecordTest.kt, devp2p/src/test/kotlin/org/apache/tuweni/devp2p/v5/storage/RoutingTableTest.kt
Add support for list entries in ENRs
=> Add support for list entries in ENRs

ethstats/src/integrationTest/java/org/apache/tuweni/ethstats/EthStatsReporterTest.java, ethstats/src/integrationTest/java/org/apache/tuweni/ethstats/FakeEthStatsServer.java, ethstats/src/main/java/org/apache/tuweni/ethstats/EthStatsReporter.java
Add a bit of testing coverage for ethstats.
=> Add test covering basic ethstats functions

codecov.yml
Its contents are largely generated and some of it is not used
=> Ignore Sodium.java 

progpow/src/main/java/org/apache/tuweni/progpow/ProgPoWMath.java, units/src/main/java/org/apache/tuweni/units/bigints/UInt32.java, units/src/main/java/org/apache/tuweni/units/bigints/UInt32Value.java, units/src/test/java/org/apache/tuweni/units/bigints/UInt32Test.java
=> UInt32 tests

crypto/src/main/java/org/apache/tuweni/crypto/Hash.java, crypto/src/test/java/org/apache/tuweni/crypto/HashTest.java, io/src/main/java/org/apache/tuweni/io/Streams.java, io/src/test/java/org/apache/tuweni/io/file/FilesTest.java, kv/src/test/java/org/apache/tuweni/kv/RedisBytesCodecTest.java, kv/src/test/kotlin/org/apache/tuweni/kv/KeyValueStoreSpec.kt
Add more tests to cover corners of io and crypto
=> Add more tests to cover corners of io and crypto

concurrent-coroutines/src/main/kotlin/org/apache/tuweni/concurrent/coroutines/AsyncCompletion.kt, concurrent-coroutines/src/test/kotlin/org/apache/tuweni/concurrent/coroutines/AsyncCompletionTest.kt, concurrent-coroutines/src/test/kotlin/org/apache/tuweni/concurrent/coroutines/AsyncResultTest.kt
Add coverage and fix a bug in concurrent coroutine functions
=> Add coverage and fix a bug in concurrent coroutine functions

bytes/src/test/java/org/apache/tuweni/bytes/DelegateMutableBytes32Test.java, bytes/src/test/java/org/apache/tuweni/bytes/DelegateMutableBytes48Test.java
=> add more tests for bytes

bytes/src/test/java/org/apache/tuweni/bytes/Bytes48Test.java, bytes/src/test/java/org/apache/tuweni/bytes/MutableBytesTest.java
Add more tests for Bytes classes.
=> Add more tests for Bytes classes

gradle/check-licenses.gradle, net-coroutines/src/integrationTest/kotlin/org/apache/tuweni/net/coroutines/CoroutineSocketChannelTest.kt
License checks failed on master for this dependency. Try resolving explicitly this dependency's license.
=> check license explicitly for this dependency

rlpx/src/main/java/org/apache/tuweni/rlpx/wire/DefaultWireConnection.java, rlpx/src/main/java/org/apache/tuweni/rlpx/wire/WireConnection.java
Expose the peer hello message of the connection, so we can get client id and other information.
=> Expose the peer hello message

RELEASE.md
Small changes to release steps.
=> Fix release steps

devp2p-eth/src/test/kotlin/org/apache/tuweni/devp2p/eth/EthSubprotocolTest.kt, eth-repository/src/main/kotlin/org/apache/tuweni/eth/repository/BlockchainRepository.kt, les/src/test/kotlin/org/apache/tuweni/les/LESSubProtocolHandlerTest.kt, les/src/test/kotlin/org/apache/tuweni/les/LESSubprotocolTest.kt
Adds a simple helper to make it easier on developers to create a repository for test and quick transient tasks.
=> Add in memory helper for BlockchainRepository

devp2p/build.gradle, devp2p/src/main/kotlin/org/apache/tuweni/devp2p/v5/Scraper.kt, dist/build.gradle
Make sure the scraper packaging works and the script works ootb.
=> Test scraper

build.gradle, dns-discovery/src/main/kotlin/org/apache/tuweni/discovery/DNSDaemon.kt, dns-discovery/src/main/kotlin/org/apache/tuweni/discovery/DNSDaemonListener.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/DNSClient.kt
=> Nicer dns daemon api

devp2p/src/main/kotlin/org/apache/tuweni/devp2p/EthereumNodeRecord.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/WireConnectionPeerRepositoryAdapter.kt, rlpx/src/integrationTest/java/org/apache/tuweni/rlpx/vertx/VertxRLPxServiceTest.java, rlpx/src/main/java/org/apache/tuweni/rlpx/MemoryWireConnectionsRepository.java, rlpx/src/main/java/org/apache/tuweni/rlpx/WireConnectionRepository.java, rlpx/src/main/java/org/apache/tuweni/rlpx/wire/DefaultWireConnection.java, rlpx/src/main/java/org/apache/tuweni/rlpx/wire/WireConnection.java, rlpx/src/test/java/org/apache/tuweni/rlpx/MemoryWireConnectionsRepositoryTest.java, rlpx/src/test/java/org/apache/tuweni/rlpx/wire/DefaultWireConnectionTest.java, rlpx/src/test/java/org/apache/tuweni/rlpx/wire/PingPongTest.java
Add listeners for connection and disconnection.
=> Add listeners for connection and disconnection

.idea/codeStyles/Project.xml, dependency-versions.gradle, dns-discovery/src/main/kotlin/org/apache/tuweni/discovery/DNSResolver.kt, dns-discovery/src/test/kotlin/org/apache/tuweni/discovery/DNSResolverTest.kt
Take care of TCP timeouts when connecting to server
Upgrade dnsjava to latest
=> Take care of TCP timeouts when connecting to server

bytes/src/main/java/org/apache/tuweni/bytes/ConcatenatedBytes.java, bytes/src/test/java/org/apache/tuweni/bytes/Bytes32Test.java
Fixes bug in code managing bytes concatenation.
fixes #186
=> Fix for bug #186

RELEASE.md, gradle/stage.gradle
Fix the URLs of the tag names in releases
=> Fix the URLs of the tag names in releases

crypto/src/main/java/org/apache/tuweni/crypto/Hash.java, crypto/src/main/java/org/apache/tuweni/crypto/sodium/LibSodium.java, crypto/src/main/java/org/apache/tuweni/crypto/sodium/SHA512Hash.java, crypto/src/main/java/org/apache/tuweni/crypto/sodium/Sodium.java, crypto/src/test/java/org/apache/tuweni/crypto/HashTest.java, crypto/src/test/java/org/apache/tuweni/crypto/sodium/SodiumTest.java
Add sodium to a few sha256 functions that can use directly 
Fixes #147
=> Add sodium to hashing

eth-faucet/build.gradle, eth-faucet/src/main/kotlin/org/apache/tuweni/faucet/FaucetApplication.kt, eth-faucet/src/main/kotlin/org/apache/tuweni/faucet/controller/FaucetController.kt, eth-faucet/src/main/kotlin/org/apache/tuweni/faucet/controller/FaucetRequest.kt, eth-faucet/src/main/resources/application.yml, eth-faucet/src/main/resources/templates/index.html
add bootstrap css to faucet, make it look nicer, display better errors
=> add bootstrap css to faucet, make it look nicer, display better errors

.gitignore, devp2p-eth/src/main/kotlin/org/apache/tuweni/devp2p/eth/ConnectionSelectionStrategy.kt, devp2p-eth/src/main/kotlin/org/apache/tuweni/devp2p/eth/EthClient.kt, devp2p-eth/src/main/kotlin/org/apache/tuweni/devp2p/eth/EthController.kt, devp2p-eth/src/main/kotlin/org/apache/tuweni/devp2p/eth/EthRequestsManager.kt, devp2p-eth/src/main/kotlin/org/apache/tuweni/devp2p/eth/EthSubprotocol.kt, dns-discovery/src/integrationTest/kotlin/org/apache/tuweni/discovery/DNSResolverTest.kt, eth-client/build.gradle, eth-client/src/integrationTest/kotlin/org/apache/tuweni/ethclient/EthereumClientRunTest.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/ConnectionManagementStrategy.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/DNSClient.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/EthereumClient.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/EthereumClientConfig.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/EthereumPeerRepository.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/FromBestBlockSynchronizer.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/FromUnknownParentSynchronizer.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/PeerStatusEthSynchronizer.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/ScoredConnectionSelectionStrategy.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/Synchronizer.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/WireConnectionPeerRepositoryAdapter.kt, eth-client/src/test/kotlin/org/apache/tuweni/ethclient/EthereumClientConfigTest.kt, eth-client/src/test/kotlin/org/apache/tuweni/ethclient/EthereumPeerRepositoryTest.kt, eth-client/src/test/kotlin/org/apache/tuweni/ethclient/WireConnectionPeerRepositoryAdapterTest.kt, eth-repository/src/main/kotlin/org/apache/tuweni/eth/repository/BlockchainRepository.kt, les/src/main/kotlin/org/apache/tuweni/les/LESSubprotocol.kt, les/src/test/kotlin/org/apache/tuweni/les/LESSubProtocolHandlerTest.kt, les/src/test/kotlin/org/apache/tuweni/les/LESSubprotocolTest.kt, peer-repository/src/main/kotlin/org/apache/tuweni/peer/repository/PeerRepository.kt, rlpx/src/main/java/org/apache/tuweni/rlpx/wire/DefaultWireConnection.java
This PR includes a set of synchronizing methods that allow the Ethereum client to sync up.
It requires more testing.
=> Add syncing capabilities for mainnet

ethstats/src/integrationTest/java/org/apache/tuweni/ethstats/EthStatsReporterTest.java, ethstats/src/integrationTest/java/org/apache/tuweni/ethstats/FakeEthStatsServer.java
Fix an ethstats client test that seems flaky - async bites.
=> Fix ethstats flaky test

build.gradle
Fix some warnings that pop up in Intellij.
=> Fix IDE warnings on gradle import

net/src/main/java/org/apache/tuweni/net/tls/ClientFingerprintTrustManager.java, net/src/main/java/org/apache/tuweni/net/tls/ServerFingerprintTrustManager.java, net/src/main/java/org/apache/tuweni/net/tls/TrustManagerFactories.java, net/src/main/java/org/apache/tuweni/net/tls/VertxTrustOptions.java, net/src/test/java/org/apache/tuweni/net/tls/ClientAllowlistTest.java, net/src/test/java/org/apache/tuweni/net/tls/ClientCaOrAllowlistTest.java, net/src/test/java/org/apache/tuweni/net/tls/ServerAllowlistTest.java, net/src/test/java/org/apache/tuweni/net/tls/ServerCaOrAllowlistTest.java
Renamed whitelist to allowlist
Fixes #217
=> Fixes #217 . Renamed whitelist to allowlist

devp2p-proxy/src/integrationTest/kotlin/org/apache/tuweni/devp2p/proxy/SendDataToAnotherNodeTest.kt, devp2p-proxy/src/main/kotlin/org/apache/tuweni/devp2p/proxy/ProxyClient.kt
Fixes a flaky test that doesn't account for an async peer connection negotiation.
=> Add a delay to client, and more assertions to catch issue

eth-client/src/main/kotlin/org/apache/tuweni/ethclient/EthereumPeerRepository.kt
Add just a bit of javadoc to the EthereumPeerRepository class.
=> Add javadoc

devp2p-eth/src/main/kotlin/org/apache/tuweni/devp2p/eth/EthClient66.kt, devp2p-eth/src/main/kotlin/org/apache/tuweni/devp2p/eth/EthController.kt, devp2p-eth/src/main/kotlin/org/apache/tuweni/devp2p/eth/EthHandler66.kt, devp2p-eth/src/main/kotlin/org/apache/tuweni/devp2p/eth/EthHelloSubprotocol.kt, devp2p-eth/src/main/kotlin/org/apache/tuweni/devp2p/eth/EthRequestsManager.kt, devp2p-eth/src/main/kotlin/org/apache/tuweni/devp2p/eth/EthSubprotocol.kt, devp2p-eth/src/test/kotlin/org/apache/tuweni/devp2p/eth/EthSubprotocolTest.kt, devp2p-proxy/src/main/kotlin/org/apache/tuweni/devp2p/proxy/ProxySubprotocol.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/EthereumClient.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/FromBestBlockSynchronizer.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/FromUnknownParentSynchronizer.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/PeerStatusEthSynchronizer.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/Synchronizer.kt, les/src/main/kotlin/org/apache/tuweni/les/LESSubProtocolHandler.kt, les/src/main/kotlin/org/apache/tuweni/les/LESSubprotocol.kt, rlp/src/main/java/org/apache/tuweni/rlp/BytesRLPReader.java, rlp/src/main/java/org/apache/tuweni/rlp/RLPReader.java, rlp/src/test/java/org/apache/tuweni/rlp/BytesRLPReaderTest.java, rlpx/src/integrationTest/java/org/apache/tuweni/rlpx/vertx/VertxAcceptanceTest.java, rlpx/src/integrationTest/java/org/apache/tuweni/rlpx/vertx/VertxRLPxServiceTest.java, rlpx/src/main/java/org/apache/tuweni/rlpx/vertx/VertxRLPxService.java, rlpx/src/main/java/org/apache/tuweni/rlpx/wire/DefaultSubProtocolIdentifier.java, rlpx/src/main/java/org/apache/tuweni/rlpx/wire/DefaultWireConnection.java, rlpx/src/main/java/org/apache/tuweni/rlpx/wire/SubProtocol.java, rlpx/src/main/java/org/apache/tuweni/rlpx/wire/SubProtocolIdentifier.java, rlpx/src/test/java/org/apache/tuweni/rlpx/wire/DefaultWireConnectionTest.java
Adds support for eth/66
Fixes #223
=> Add support for eth/66

build.gradle
=> Fix pom artifactId

evm/src/main/kotlin/org/apache/tuweni/evm/impl/berlin/OpCodes.kt, units/src/main/java/org/apache/tuweni/units/bigints/BaseUInt256Value.java, units/src/main/java/org/apache/tuweni/units/bigints/UInt256.java, units/src/main/java/org/apache/tuweni/units/bigints/UInt256Value.java, units/src/main/java/org/apache/tuweni/units/bigints/UInt32Value.java, units/src/main/java/org/apache/tuweni/units/bigints/UInt384Value.java, units/src/main/java/org/apache/tuweni/units/bigints/UInt64Value.java, units/src/test/java/org/apache/tuweni/units/bigints/UInt256Test.java, units/src/test/java/org/apache/tuweni/units/bigints/UInt32Test.java, units/src/test/java/org/apache/tuweni/units/bigints/UInt384Test.java, units/src/test/java/org/apache/tuweni/units/bigints/UInt64Test.java, units/src/test/java/org/apache/tuweni/units/ethereum/WeiTest.java
Some fixes to how UInt classes handle toLong and toBigInteger to be consistent.
Fixes #247
=> UInt compat fixes

eth-crawler/src/main/kotlin/org/apache/tuweni/eth/crawler/RelationalPeerRepository.kt
=> Reduce crawler logging

devp2p-eth/src/main/kotlin/org/apache/tuweni/devp2p/eth/EthHandler.kt, devp2p-eth/src/main/kotlin/org/apache/tuweni/devp2p/eth/EthHandler66.kt, devp2p-eth/src/main/kotlin/org/apache/tuweni/devp2p/eth/EthHelloHandler.kt, eth-crawler/src/main/kotlin/org/apache/tuweni/eth/crawler/CrawlerApp.kt, eth-crawler/src/main/kotlin/org/apache/tuweni/eth/crawler/RelationalPeerRepository.kt, eth-crawler/src/main/resources/db/migration/V1_3_0__add_disconnect_reason.sql, rlpx/src/main/java/org/apache/tuweni/rlpx/wire/DefaultWireConnection.java
Right now we only would report a connection status if it really managed to get through checks.
We instead should be able to report even if we decide to disconnect from the peer, so the repository can take appropriate action.
=> Report status on all connections

devp2p/src/main/kotlin/org/apache/tuweni/devp2p/Scraper.kt, eth-crawler/src/main/kotlin/org/apache/tuweni/eth/crawler/CrawlerApp.kt, eth-crawler/src/main/kotlin/org/apache/tuweni/eth/crawler/RelationalPeerRepository.kt, rlpx/src/main/java/org/apache/tuweni/rlpx/vertx/VertxRLPxService.java
Nits picked up while debugging the crawler
=> nits to connect to peers non-stop

eth-client/src/main/kotlin/org/apache/tuweni/ethclient/EthereumClient.kt
Close the CacheManager: DefaultCacheManager and headersCache
fixes: #259
=> Close cache manager

devp2p/src/main/kotlin/org/apache/tuweni/devp2p/DiscoveryService.kt, eth-crawler/src/main/kotlin/org/apache/tuweni/eth/crawler/RelationalPeerRepository.kt, eth-crawler/src/main/kotlin/org/apache/tuweni/eth/crawler/rest/ClientVersion.kt, eth-crawler/src/main/kotlin/org/apache/tuweni/eth/crawler/rest/ClientsService.kt
Add stats endpoint for London.
=> add london stats

eth-crawler/src/main/resources/webapp/index.html
=> Fix displaying public key

eth-crawler/src/main/kotlin/org/apache/tuweni/eth/crawler/CrawlerApp.kt, eth-crawler/src/main/kotlin/org/apache/tuweni/eth/crawler/CrawlerConfig.kt, eth-crawler/src/main/kotlin/org/apache/tuweni/eth/crawler/CrawlerRESTService.kt, eth-crawler/src/main/kotlin/org/apache/tuweni/eth/crawler/RelationalPeerRepository.kt
Remove configuration TODOs, move to config.
=> Configure TODOs - move to config

eth-crawler/src/main/resources/webapp/index.html
Crawler UI: Render hashes with ellipses to show all data on a page
=> Render hashes with ellipses to show all data on a page

jsonrpc-app/src/main/kotlin/org/apache/tuweni/jsonrpc/app/JSONRPCApp.kt, jsonrpc-app/src/main/kotlin/org/apache/tuweni/jsonrpc/app/JSONRPCConfig.kt, jsonrpc/src/main/kotlin/org/apache/tuweni/jsonrpc/methods/MethodsHandler.kt, jsonrpc/src/test/kotlin/org/apache/tuweni/jsonrpc/methods/MethodsHandlerTest.kt
Add method allowlist for JSON-RPC server.
Fixes #300
=> Add allowlist

eth/src/main/kotlin/org/apache/tuweni/eth/JSONRPCRequest.kt, eth/src/main/kotlin/org/apache/tuweni/eth/JSONRPCResponse.kt, jsonrpc-app/src/main/kotlin/org/apache/tuweni/jsonrpc/app/JSONRPCApp.kt, jsonrpc-app/src/main/kotlin/org/apache/tuweni/jsonrpc/app/JSONRPCConfig.kt, jsonrpc/src/main/kotlin/org/apache/tuweni/jsonrpc/JSONRPCClient.kt, jsonrpc/src/main/kotlin/org/apache/tuweni/jsonrpc/methods/MethodsHandler.kt, jsonrpc/src/test/kotlin/org/apache/tuweni/jsonrpc/methods/MethodsHandlerTest.kt
Connects our proxy server to a JSON-RPC client actually calling out to an endpoint
Related to #322
=> Add JSON-RPC client to talk to endpoint

jsonrpc-app/src/main/kotlin/org/apache/tuweni/jsonrpc/app/JSONRPCApp.kt, jsonrpc/src/main/kotlin/org/apache/tuweni/jsonrpc/JSONRPCClient.kt
Make sure to report an error if the backend is unavailable.
Related to #323
=> respond with an error if the backend is unavailable

jsonrpc-app/src/main/kotlin/org/apache/tuweni/jsonrpc/app/JSONRPCApp.kt, jsonrpc-app/src/main/kotlin/org/apache/tuweni/jsonrpc/app/JSONRPCConfig.kt, jsonrpc/src/main/kotlin/org/apache/tuweni/jsonrpc/JSONRPCClient.kt
Add basic auth credentials to pass to the endpoint.
Related to #322
=> Pass credentials to endpoint

jsonrpc/build.gradle, jsonrpc/src/main/kotlin/org/apache/tuweni/jsonrpc/methods/MethodsHandler.kt, jsonrpc/src/test/kotlin/org/apache/tuweni/jsonrpc/methods/MethodsHandlerTest.kt
Add a handler able to cache some requests.
Fixes #308
=> add caching handler

jsonrpc-app/build.gradle, jsonrpc-app/src/main/kotlin/org/apache/tuweni/jsonrpc/app/JSONRPCApp.kt, jsonrpc-app/src/main/kotlin/org/apache/tuweni/jsonrpc/app/JSONRPCConfig.kt
Add caching and throttling to the app. Add config parameters.
=> Add caching to app

eth-crawler/src/main/kotlin/org/apache/tuweni/eth/crawler/RelationalPeerRepository.kt, eth-crawler/src/main/kotlin/org/apache/tuweni/eth/crawler/rest/ClientIdInfo.kt, eth-crawler/src/main/kotlin/org/apache/tuweni/eth/crawler/rest/ClientsService.kt, eth-crawler/src/test/kotlin/org/apache/tuweni/eth/crawler/rest/ClientIdInfoTest.kt
Adds client version stats to the crawler data.
=> Add client version stats

examples/jsonrpc/README.md, examples/jsonrpc/config.toml, examples/jsonrpc/docker-compose.yml, examples/jsonrpc/logback.xml, examples/jsonrpc/otel-collector-config.yml, jsonrpc-app/src/main/kotlin/org/apache/tuweni/jsonrpc/app/JSONRPCApp.kt, jsonrpc-app/src/main/kotlin/org/apache/tuweni/jsonrpc/app/JSONRPCConfig.kt, metrics/build.gradle, metrics/src/main/kotlin/org/apache/tuweni/metrics/MetricsService.kt
=> initial sample

jsonrpc-app/src/main/kotlin/org/apache/tuweni/jsonrpc/app/JSONRPCApp.kt, jsonrpc-app/src/main/kotlin/org/apache/tuweni/jsonrpc/app/JSONRPCConfig.kt, jsonrpc/src/main/kotlin/org/apache/tuweni/jsonrpc/methods/MethodsHandler.kt
Add expiration and lifespan configuration to the cache used to cache requests.
=> Add expiration and lifespan config

jsonrpc-app/src/main/kotlin/org/apache/tuweni/jsonrpc/app/JSONRPCApp.kt, jsonrpc/src/main/kotlin/org/apache/tuweni/jsonrpc/JSONRPCServer.kt, metrics/src/main/kotlin/org/apache/tuweni/metrics/MetricsService.kt
Tuning tracing to report more traces
Set the service name on traces.
=> Tuning tracing to report more traces

devp2p/build.gradle, jsonrpc/build.gradle
=> remove logback runtime dependencies

devp2p-proxy/build.gradle, devp2p-proxy/src/main/kotlin/org/apache/tuweni/devp2p/proxy/TcpEndpoint.kt, eth-client/build.gradle, eth-client/src/integrationTest/kotlin/org/apache/tuweni/ethclient/ProxyEthereumClientTest.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/EthereumClient.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/EthereumClientConfig.kt
Adds proxy capabilities to the Tuweni client.
#227
=> Work on proxy client

.github/workflows/docs.yml, build.gradle, devp2p/src/main/kotlin/org/apache/tuweni/devp2p/DiscoveryService.kt, dist/build.gradle, gradle.properties
reinstate docs build, upgrade dokka to 1.6.10 to support latest Kotlin.
=> reinstate docs build, upgrade dokka

eth-client-app/src/main/resources/bootnode.toml, eth-client/src/integrationTest/kotlin/org/apache/tuweni/ethclient/EthereumClientRunTest.kt, eth-client/src/integrationTest/kotlin/org/apache/tuweni/ethclient/ProxyEthereumClientTest.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/EthereumClient.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/EthereumClientConfig.kt, eth-client/src/main/resources/default.toml, eth-client/src/test/kotlin/org/apache/tuweni/ethclient/EthereumClientConfigTest.kt
Read peer repositories from TOML.
Fixes #263
=> Add peer repository reading from TOML

devp2p-eth/src/main/kotlin/org/apache/tuweni/devp2p/eth/EthClient.kt, devp2p-eth/src/main/kotlin/org/apache/tuweni/devp2p/eth/EthClient66.kt, devp2p-eth/src/main/kotlin/org/apache/tuweni/devp2p/eth/EthHandler.kt, devp2p-eth/src/main/kotlin/org/apache/tuweni/devp2p/eth/EthHandler66.kt, devp2p-eth/src/test/kotlin/org/apache/tuweni/devp2p/eth/EthHandlerTest.kt, rlpx/src/main/java/org/apache/tuweni/rlpx/wire/WireConnection.java
Change API to reflect what the method does.
Fixes #256
=> agreedSubprotocol->agreedSubprotocolVersion

.github/workflows/checks.yml, NOTICE, build.gradle
Checks that the NOTICE file has the correct year, and update the year on the NOTICE file.
=> check NOTICE

eth-client/src/main/kotlin/org/apache/tuweni/ethclient/EthereumClient.kt
Move all stores of the ethereum client to Infinispan.
Fixes #260
=> move all stores to infinispan

build.gradle
Publish jars as modules
fixes #206
=> Publish jars as modules

devp2p-proxy/src/main/kotlin/org/apache/tuweni/devp2p/proxy/TcpDownstream.kt, devp2p-proxy/src/main/kotlin/org/apache/tuweni/devp2p/proxy/TcpUpstream.kt, eth-client/build.gradle, eth-client/src/integrationTest/kotlin/org/apache/tuweni/ethclient/ProxyEthereumClientTest.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/EthereumClient.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/EthereumClientConfig.kt, eth-client/src/test/kotlin/org/apache/tuweni/ethclient/EthereumClientConfigTest.kt, rlpx/src/main/java/org/apache/tuweni/rlpx/vertx/VertxRLPxService.java
Adds an integration test for proxies.
Adds features such as a downstream TCP server for clients to call into the proxy.
=> Add proxy integration test - and fix what was missing to make it pass

devp2p-eth/src/main/kotlin/org/apache/tuweni/devp2p/eth/EthHandler.kt, devp2p-eth/src/main/kotlin/org/apache/tuweni/devp2p/eth/EthHandler66.kt, devp2p-eth/src/test/kotlin/org/apache/tuweni/devp2p/eth/EthHandlerTest.kt, eth-client/src/integrationTest/kotlin/org/apache/tuweni/ethclient/EthereumClientRunTest.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/EthereumClient.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/EthereumPeerRepository.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/Synchronizer.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/WireConnectionPeerRepositoryAdapter.kt, rlp/src/main/java/org/apache/tuweni/rlp/BytesRLPReader.java, rlp/src/test/java/org/apache/tuweni/rlp/BytesRLPReaderTest.java, rlpx/src/main/java/org/apache/tuweni/rlpx/wire/DefaultWireConnection.java
Fixes several issues during the connection between 2 ethereum clients, especially with eth/66.
Fixes #257
=> Fix a series of issues blocking 2 clients from talking to each other

config/src/main/java/org/apache/tuweni/config/PropertyValidator.java, config/src/test/java/org/apache/tuweni/config/PropertyValidatorTest.java, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/EthereumClient.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/EthereumClientConfig.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/FromBestBlockHeaderSynchronizer.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/FromUnknownParentSynchronizer.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/PeerStatusEthSynchronizer.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/Synchronizer.kt
Make synchronizers configurable, add a from/to.
=> Make synchronizers configurable

kv/src/main/kotlin/org/apache/tuweni/kv/EntityManagerKeyValueStore.kt, kv/src/main/kotlin/org/apache/tuweni/kv/InfinispanKeyValueStore.kt, kv/src/main/kotlin/org/apache/tuweni/kv/KeyValueStore.kt, kv/src/main/kotlin/org/apache/tuweni/kv/LevelDBKeyValueStore.kt, kv/src/main/kotlin/org/apache/tuweni/kv/MapDBKeyValueStore.kt, kv/src/main/kotlin/org/apache/tuweni/kv/MapKeyValueStore.kt, kv/src/main/kotlin/org/apache/tuweni/kv/ProxyKeyValueStore.kt, kv/src/main/kotlin/org/apache/tuweni/kv/RedisKeyValueStore.kt, kv/src/main/kotlin/org/apache/tuweni/kv/RocksDBKeyValueStore.kt, kv/src/main/kotlin/org/apache/tuweni/kv/SQLKeyValueStore.kt, kv/src/test/kotlin/org/apache/tuweni/kv/KeyValueStoreSpec.kt
Adds a remove method to any KV store so we may explicitly remove values.
=> add remove method to kv

evm/src/main/kotlin/org/apache/tuweni/evm/EthereumVirtualMachine.kt, evm/src/main/kotlin/org/apache/tuweni/evm/TransactionalEVMHostContext.kt, evm/src/main/kotlin/org/apache/tuweni/evm/impl/EvmVmImpl.kt, evm/src/test/kotlin/org/apache/tuweni/evm/EVMReferenceTest.kt
Expose the execution changes of the EVM
=> expose the evm execution changes

eth/src/main/java/org/apache/tuweni/eth/EthJsonModule.java
Add support for bytes32 ser/deserialization
=> Add support for bytes32 ser/deserialization

gossip/src/main/java/org/apache/tuweni/gossip/GossipApp.java, plumtree/src/integrationTest/java/org/apache/tuweni/plumtree/vertx/VertxGossipServerTest.java, plumtree/src/main/java/org/apache/tuweni/plumtree/MessageListener.java, plumtree/src/main/java/org/apache/tuweni/plumtree/MessageSender.java, plumtree/src/main/java/org/apache/tuweni/plumtree/State.java, plumtree/src/main/java/org/apache/tuweni/plumtree/vertx/VertxGossipServer.java, plumtree/src/test/java/org/apache/tuweni/plumtree/StateTest.java
=> Ability to send a message to a peer

evm/src/main/kotlin/org/apache/tuweni/evm/EthereumVirtualMachine.kt, evm/src/main/kotlin/org/apache/tuweni/evm/impl/EvmVmImpl.kt, evm/src/test/kotlin/org/apache/tuweni/evm/EthereumVirtualMachineTest.kt
Add a listener that can stop execution
=> Add a way to halt the EVM execution

build.gradle
checkLicenses is no longer in use, remove from aliases.
=> remove checkLicences

eth-blockprocessor/src/main/kotlin/org/apache/tuweni/blockprocessor/BlockProcessor.kt, eth-blockprocessor/src/main/kotlin/org/apache/tuweni/blockprocessor/ProtoBlock.kt, eth-repository/src/main/kotlin/org/apache/tuweni/eth/repository/BlockchainRepository.kt, eth-repository/src/main/kotlin/org/apache/tuweni/eth/repository/StateRepository.kt, eth-repository/src/main/kotlin/org/apache/tuweni/eth/repository/TransientStateRepository.kt
Makes the block processor use a transient state and return it at the end of the execution, so it can be applied if the block is sealed.
=> make the processor use a transient state

jsonrpc/src/main/kotlin/org/apache/tuweni/jsonrpc/methods/MethodsHandler.kt, jsonrpc/src/main/kotlin/org/apache/tuweni/jsonrpc/methods/Net.kt, jsonrpc/src/test/kotlin/org/apache/tuweni/jsonrpc/methods/NetTest.kt
=> Add more JSON-RPC methods

crypto/src/main/java/org/apache/tuweni/crypto/DecryptionException.java, crypto/src/main/java/org/apache/tuweni/crypto/EncryptionException.java, crypto/src/main/java/org/apache/tuweni/crypto/SECP256K1.java, crypto/src/test/java/org/apache/tuweni/crypto/SECP256K1Test.java
Add methods to encrypt and decrypt data with secp256k1 keys.
=> Add methods to encrypt and decrypt with secp256k1

eth-blockprocessor/src/main/kotlin/org/apache/tuweni/blockprocessor/BlockProcessor.kt
The block processor previously didn't know what to do with a transaction creating a new contract.
=> Support running the EVM when there is a new contract

devp2p-eth/src/main/kotlin/org/apache/tuweni/devp2p/eth/EthController.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/EthereumClientConfig.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/PeerStatusEthSynchronizer.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/Synchronizer.kt
* Make status sync recursive
* Fix iterating over bodies
* Fix config of synchronizers
* Add logging
=> Make status sync recursive, and fix issues found

genesis/src/main/kotlin/org/apache/tuweni/genesis/Quorum.kt
Output validator address when outputting validators
=> Output validator address when outputting validators

evm/build.gradle
Fix a copy pasta typo on description of a gradle module
=> fix EVM gradle module description

README.md
remove docker install step from README
=> remove docker install step from README

evm-dsl/src/main/kotlin/org/apache/tuweni/evmdsl/Code.kt, evm-dsl/src/main/kotlin/org/apache/tuweni/evmdsl/Instructions.kt, evm-dsl/src/test/kotlin/org/apache/tuweni/evmdsl/CodeTest.kt
Add code that validates the EVM code given.
=> Add code to validate EVM code

.github/workflows/test_referencetests.yml, evm/build.gradle, evm/src/test/kotlin/org/apache/tuweni/evm/EVMReferenceTest.kt, evm/src/test/kotlin/org/apache/tuweni/evm/EvmCertificationTest.kt, evm/src/test/kotlin/org/apache/tuweni/evm/OpcodeTest.kt
=> try to run reference tests separately

evm-dsl/src/test/kotlin/org/apache/tuweni/evmdsl/CodeTest.kt
Just add a test to create a hello world code.
=> add a test for creating some code

eth-client/src/main/kotlin/org/apache/tuweni/ethclient/DNSClient.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/EthereumClient.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/EthereumClientConfig.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/sync/CanonicalSynchronizer.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/sync/FromBestBlockHeaderSynchronizer.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/sync/FromUnknownParentSynchronizer.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/sync/PeerStatusEthSynchronizer.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/sync/Synchronizer.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/validator/Validator.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/validator/Validators.kt, eth-client/src/test/kotlin/org/apache/tuweni/ethclient/validator/ValidatorsTest.kt, eth-repository/src/main/kotlin/org/apache/tuweni/eth/repository/BlockchainIndex.kt, eth-repository/src/main/kotlin/org/apache/tuweni/eth/repository/BlockchainRepository.kt, eth-repository/src/main/kotlin/org/apache/tuweni/eth/repository/IndexResult.kt, eth-repository/src/test/kotlin/org/apache/tuweni/eth/repository/BlockchainRepositoryTest.kt
Adds a set of validators that can validate block data before it is inserted in a repository.
Makes synchronizers choose their service, peer repository and blockchain repository, allowing us to have multiple synchronizers work alongside multiple repositories.
=> Validators

jsonrpc-app/src/main/kotlin/org/apache/tuweni/jsonrpc/app/JSONRPCConfig.kt, jsonrpc-app/src/test/kotlin/org/apache/tuweni/jsonrpc/app/JSONRPCConfigTest.kt
Add test and better defaults for the JSON-RPC proxy
=> Add test and better defaults for the JSON-RPC proxy

stratum/proxy/src/main/kotlin/org/apache/tuweni/stratum/StratumServerApp.kt
Log a warning if eth_getWork returns an error
=> Handle the case where the client is not ready to mine yet

README.md
Fix maven central badge, still pointing at old release
=> fix maven central badge

devp2p-eth/src/main/kotlin/org/apache/tuweni/devp2p/eth/BlockchainInformation.kt, devp2p-eth/src/main/kotlin/org/apache/tuweni/devp2p/eth/EthHandler.kt, devp2p-eth/src/main/kotlin/org/apache/tuweni/devp2p/eth/EthHandler66.kt, devp2p-eth/src/main/kotlin/org/apache/tuweni/devp2p/eth/EthHelloHandler.kt, devp2p-eth/src/test/kotlin/org/apache/tuweni/devp2p/eth/BlockchainInformationTest.kt, eth/src/main/java/org/apache/tuweni/eth/genesis/GenesisFile.java, eth/src/main/resources/genesis/ropsten.json, rlpx/src/main/java/org/apache/tuweni/rlpx/wire/DefaultWireConnection.java, rlpx/src/main/java/org/apache/tuweni/rlpx/wire/DisconnectMessage.java
Fix how we handle new peers with an expiringmap rather than a soft reference map.
Use proper hard fork ids.
With eth/66, don't use a request-id for all messages.
=> Eth66 status

eth-client-ui/build.gradle, eth-client-ui/src/integrationTest/kotlin/org/apache/tuweni/ethclientui/UIIntegrationTest.kt, eth-client-ui/src/main/kotlin/org/apache/tuweni/ethclientui/JSONProvider.kt, eth-client-ui/src/main/kotlin/org/apache/tuweni/ethclientui/StateService.kt, eth-client-ui/src/main/kotlin/org/apache/tuweni/ethclientui/UI.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/EthereumClient.kt
Expose the state of the client via a new UI
=> expose information from the rlpx service in the UI

eth-client/src/main/kotlin/org/apache/tuweni/ethclient/WireConnectionPeerRepositoryAdapter.kt, eth-client/src/main/resources/logback.xml
Add a bit more logging when trying to pick a peer, and set up a good production logback.xml for the client
=> expose more logging and set up sane logging when using the client

evm-dsl/src/main/kotlin/org/apache/tuweni/evmdsl/Code.kt, evm-dsl/src/main/kotlin/org/apache/tuweni/evmdsl/Instructions.kt, evm-dsl/src/test/kotlin/org/apache/tuweni/evmdsl/CodeTest.kt
Add support for entering a random new opcode in the DSL, so folks can use their new opcode to generate EVM bytecode.
=> Add support for new custom opcode in DSL

build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties
=> upgrade gradle to 7.5

eth-client/src/main/resources/logback.xml
Filter logs for rlpx - info at least.
=> Add more filters for logback

bytes/src/main/java/org/apache/tuweni/bytes/Bytes.java, bytes/src/test/java/org/apache/tuweni/bytes/BytesTest.java, evm-dsl/src/main/kotlin/org/apache/tuweni/evmdsl/Code.kt, evm-dsl/src/main/kotlin/org/apache/tuweni/evmdsl/Deployment.kt, evm-dsl/src/main/kotlin/org/apache/tuweni/evmdsl/Instructions.kt, evm-dsl/src/test/kotlin/org/apache/tuweni/evmdsl/CodeTest.kt, evm-dsl/src/test/kotlin/org/apache/tuweni/evmdsl/DeploymentTest.kt
Adds a Deployment helper method to deploy EVM bytecode.
=> Add Deployment helper to help deploy code

devp2p-eth/build.gradle, devp2p-eth/src/main/kotlin/org/apache/tuweni/devp2p/eth/EthClient66.kt, devp2p-eth/src/main/kotlin/org/apache/tuweni/devp2p/eth/EthController.kt, devp2p-eth/src/test/kotlin/org/apache/tuweni/devp2p/eth/EthControllerTest.kt
Handle when headers don't match bodies
=> Handle when headers don't match bodies

devp2p-eth/src/main/kotlin/org/apache/tuweni/devp2p/eth/BlockchainInformation.kt
Fix integration tests, define a default fork id.
=> fix integration tests

evm/src/test/kotlin/org/apache/tuweni/evm/EVMBrokenMetreAttack.kt, gradle/stage.gradle, les/src/test/kotlin/org/apache/tuweni/les/LESSubprotocolTest.kt
Cherry-pick the fixes applied to branch 2.3 to help with the release
=> Cherry pick 2.3

dependency-versions.gradle, dist/LICENSE-binary, dns-discovery/build.gradle, dns-discovery/src/integrationTest/java/org/apache/tuweni/discoveryint/DiscoveryAPITest.java, dns-discovery/src/integrationTest/kotlin/org/apache/tuweni/discovery/DNSResolverTest.kt, dns-discovery/src/main/kotlin/org/apache/tuweni/discovery/DNSDaemon.kt, dns-discovery/src/main/kotlin/org/apache/tuweni/discovery/DNSResolver.kt, dns-discovery/src/test/kotlin/org/apache/tuweni/discovery/DNSResolverTest.kt, eth-blockprocessor/build.gradle, eth-client/build.gradle, eth-client/src/integrationTest/kotlin/org/apache/tuweni/ethclient/DNSClientRunTest.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/DNSClient.kt, eth-client/src/main/kotlin/org/apache/tuweni/ethclient/EthereumClient.kt, eth-client/src/main/resources/logback.xml, eth-crawler/build.gradle, eth-crawler/src/main/kotlin/org/apache/tuweni/eth/crawler/CrawlerApp.kt, jsonrpc-app/build.gradle
Remove dnsjava, prefer vertx throughout
=> remove dnsjava, prefer vertx throughout

.github/dependabot.yml
Use dependabot for updates of gradle and github actions.
=> use dependabot for updates

eth-client-ui/build.gradle
remove unused dependency `spring-boot-starter-hateoas`
=> remove unused dependency

config/src/test/java/org/apache/tuweni/config/PropertyValidatorTest.java
Adds tests for property validators related to port validation.
Fixes #253
=> add tests for property validators related to ports. 

.github/workflows/close-stale.yml, .github/workflows/mark-issues-as-stale.yml, .github/workflows/scripts/mark-issues-as-stale.sh
Adds a new workflow to manage PRs and issues to close old inactive issues and pull requests.
=> add a workflow to mark issues and PR stale

dist/NOTICE-binary
=> Add OpenTelemetry to binary notice

bytes/README.md, units/README.md
repurpose documentation into README content to help users get started with Tuweni faster.
Relates to #67
=> add README for bytes and uints

eth-client/README.md, eth-crawler/README.md, eth-faucet/README.md, gossip/README.md, hobbits-relayer/README.md, jsonrpc-app/README.md, net/README.md
=> more READMEs

ethstats/README.md, ethstats/build.gradle, ethstats/src/main/kotlin/org/apache/tuweni/ethstats/opentelemetry/OpenTelemetryServerController.kt
=> Ethstats docs

crypto/src/main/java/org/apache/tuweni/crypto/sodium/Box.java, crypto/src/test/java/org/apache/tuweni/crypto/sodium/BoxTest.java
=> Fix issue #524

jsonrpc/src/main/kotlin/org/apache/tuweni/jsonrpc/JSONRPCClient.kt, jsonrpc/src/test/kotlin/org/apache/tuweni/jsonrpc/JSONRPCClientTest.kt
Adds support for eth_getBlockByNumber
=> Support eth_getBlockByNumber from JSONRPC client
